### PR TITLE
fix: range-constraint and lenght-constraint work with only one bound

### LINKED ISSUE #533: [BUG] <Length constraint does not work if one of the min or max values are mentioned and not both of them>
## Steps to reproduce
1.

pipeline SemiconductorBandGapsPipeline {

    block SemiconductorBandGapsExtractor oftype HttpExtractor {
		url: "https://figshare.com/ndownloader/files/31781996";
	}

	block ZipArchiveInterpreter oftype ArchiveInterpreter {
		archiveType: "zip";
	}

	block SemiconductorBandGapsCSVPicker oftype FilePicker {
		path: "/Bandpgap_database_v2/Bandgap.csv";
	}
	
	block SemiconductorBandGapsTextFileInterpreter oftype TextFileInterpreter {
	}

	block SemiconductorBandGapsCSVInterpreter oftype CSVInterpreter {
		delimiter: ",";
	}

// 	Removed white spaces from the Composition formula and kept only those rows in the format of {'element_scientific_name': units}
	valuetype Composition oftype text {
		constraints: [NonEmptyText];
	}

	constraint NonEmptyText oftype LengthConstraint {
		minLength: 1;
		// maxLength:9007199254740991;
	}
// 	DOI Format has been constrained by a standard pattern, eg: 10.1007/xxxx

	valuetype DOIReference oftype text {
		constraints: [DOIFormat];
	}

	constraint DOIFormat oftype RegexConstraint{
		regex: /\b10\.\d{4}\/[^\s]+\b/;

	}

	block SemiconductorBandGapsTableInterpreter oftype TableInterpreter {
		header: true;
		columns: [
			"Name" oftype text,
			"Composition" oftype Composition,
			"Value" oftype text,
			"Unit" oftype text,
			"Raw_value" oftype decimal,
			"Raw_unit" oftype text,
			"Snowball" oftype boolean,
			"Confidence" oftype decimal,
            "AutoSentenceParser" oftype boolean,
            "BandgapDB" oftype boolean,
            "Text" oftype text,
            "Publisher" oftype text,
            "DOI" oftype DOIReference,
            "Temperature_value" oftype text,
            "Temperature_unit" oftype text,
            "Temperature_raw_value" oftype decimal,
            "Temperature_raw_unit" oftype text,
            "Notes" oftype text,
		];
	}

	block SemiconductorBandGapsDatabaseLoader oftype SQLiteLoader {
		table: "SemiConductorBandGaps";
		file: "./SemiConductorBandGaps.sqlite";
	}

	SemiconductorBandGapsExtractor
		-> ZipArchiveInterpreter
		-> SemiconductorBandGapsCSVPicker
		-> SemiconductorBandGapsTextFileInterpreter
		-> SemiconductorBandGapsCSVInterpreter
		-> SemiconductorBandGapsTableInterpreter
		-> SemiconductorBandGapsDatabaseLoader;
	
}

## Description
- Expected: SQLite Database named SemiConductorBandGaps.sqlite to be created. No error to be encountered in the execution of the code.
- Actual:

Error encountered. 

                error: An unknown error occurred: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.strict)(valuetype.isInternalValueRepresentation(defaultValue))

    at ExecutionContext.getDefaultPropertyValue (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:974:29)
    at ExecutionContext.getPropertyValue (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:945:25)
    at LengthConstraintExecutor.isValid (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:607:35)
    at ValueRepresentationValidityVisitor.visitAtomicValuetype (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:2065:65)
    at AtomicValuetype.acceptVisitor (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:12713:24)
    at isValidValueRepresentation (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:2046:22)
    at TableInterpreterExecutor.parseAndValidateValue (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:4546:64)
    at C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:4525:38
    at Array.forEach (<anonymous>)
    at TableInterpreterExecutor.constructAndValidateTableRow (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:4520:23)
    at C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:4508:35
    at Array.forEach (<anonymous>)
    at Sheet.iterateRows (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:1673:19)
    at TableInterpreterExecutor.constructAndValidateTable (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:4504:15)
    at TableInterpreterExecutor.<anonymous> (C:\Users\conne\AppData\Roaming\npm\node_modules\@jvalue\jayvee-interpreter\main.js:4489:41)
    at Generator.next (<anonymous>)
                $In /D:/Project 2/4th last/SemiconductorBandGapsModel.jv:42:8
                42 |     block SemiconductorBandGapsTableInterpreter oftype TableInterpreter {

### PR DESCRIPTION
**Pull request by TungstnBallon**
It is now possible to only specify one bound when using `lenght-constraint`. However one bound minimum is still required
closes #533

I went ahead and took the liberty to also implement this fix for `range-constraint`.

### CODE REVIEW

File: libs/execution/src/lib/constraints/executors/length-constraint-executor.ts [hunk 1]
```diff
@@ -24,15 +26,25 @@ export class LengthConstraintExecutor implements ConstraintExecutor {
...
+      return minLength <= value.length && value.length <= maxLength;
+    } else if (minLength !== undefined) {
+      return minLength <= value.length;
+    } else if (maxLength !== undefined) {
+      return value.length <= maxLength;
+    }
+
+    // FIXME: throw an actual error?
+    assert(true); // here: minLength === undefined && maxLength === undefined
+    return false; // HACK: linter complains about a missing return type otherwise
```
Comment (TungstnBallon) [inline libs/execution/src/lib/constraints/executors/length-constraint-executor.ts:48]: @rhazn I was unsure what to do if no bound is specified

File: libs/execution/src/lib/constraints/executors/range-constraint-executor.ts [hunk 2]
```diff
@@ -29,31 +31,39 @@ export class RangeConstraintExecutor implements ConstraintExecutor {
...
+    assert(upperBoundInclusive !== undefined); // upperBoundInclusive has a default value
 
-    const lowerBoundFulfilled = lowerBoundInclusive
-      ? lowerBound <= numericValue
-      : lowerBound < numericValue;
-
-    const upperBoundFulfilled = upperBoundInclusive
-      ? numericValue <= upperBound
-      : numericValue < upperBound;
+    assert(upperBound !== undefined || lowerBound !== undefined); // FIXME: throw an actual errror?
```
Comment (TungstnBallon) [inline libs/execution/src/lib/constraints/executors/range-constraint-executor.ts:53]: see https://github.com/jvalue/jayvee/pull/548/files#r1565882788

File: libs/execution/src/lib/constraints/executors/length-constraint-executor.ts (hunk 1 above)
Comment (TungstnBallon) [reply libs/execution/src/lib/constraints/executors/length-constraint-executor.ts:48]: As discussed during today's meeting I will handle this by letting all values pass through a constraint without bounds. To compensate this I'm going to add a language server warning.

**Review by rhazn — CHANGES_REQUESTED** [review]
Thanks for the fix and great that you also expanded it to other constraint types, well done 🥳 . I think the approach taken is not the perfect one though, I left a comment on the `execution-context` towards that.

As always, I could be wrong so if there is a reason why you chose to not go the default value route let me know, otherwise I think it would be better to approach it like that.

File: libs/execution/test/assets/length-constraint-executor/only-lower-bound.jv [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+pipeline TestPipeline {
+
+  block TestExtractor oftype TestFileExtractor {
+  }
+
+  block TestLoader oftype TestTableLoader {
+  }
+
+  block TestProperty oftype TestProperty {
+		valuetypeAssignmentProperty: "test" oftype ConstraintType;
```
Comment (rhazn) [inline libs/execution/test/assets/length-constraint-executor/only-lower-bound.jv:24]:
```suggestion
		valuetypeAssignmentProperty: "test" oftype TestValueType;
```

Not sure how this model even compiles?! 🤔 Same for the other model.

**Review by rhazn — CHANGES_REQUESTED** [review]
I might be missing something but there are no functional changes in this PR, only tests and hints now? Did you merge the functional changes in a different PR?

**Comment by TungstnBallon** [comment]
> I might be missing something but there are no functional changes in this PR, only tests and hints now? Did you merge the functional changes in a different PR?

It seems to work without functional changes. I think this is because all the required properties like `lowerBound` or `lowerBoundInclusive` already have defaults that are used if the property isn't specified in the `.jv` file.
I followed the steps to reproduce from #533 and the error described there is gone too.

**Review by rhazn — APPROVED** [review]
Sounds good, then we have hardened Jayvee for the future with more tests :). For future reference, if you'd like me to review again please always click the re-request review button though.
